"""change data fields

Revision ID: aa2af37572ad
Revises: 6c5ef3826d6d
Create Date: 2024-05-11 23:10:23.351289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2af37572ad'
down_revision: Union[str, None] = '6c5ef3826d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('cost_per_hour', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'cost_per_hour')
    # ### end Alembic commands ###
